title:              "Javier Conde"
special_title:      "<span class='special_title'>J</span><span>avier</span> <span class='special_title'> C</span><span>onde</span>"
description:        "<span class='links_underlined'>Researcher and Ph.D. student at <a href='https://www.upm.es/' target='_blank'>UPM</a> and member of <a href='http://ging.github.io/' target='_blank'>GING</a></span>"

url:                "null"
author:             "javicond3"
email:              "4b3javi(at)gmail.com"
location:           "Madrid, Spain"
github:             "javicond3"
linkedin:           "javier-conde-diaz"
google_analytics:   "G-NH74ZGDKHG"


baseurl:            ""

markdown:           kramdown

nav:
  - name:           "About me"
    href:           "/about"
  - name:           "Projects"
    href:           "/projects"
  - name:           "Research"
    href:           "/research"
  - name:           "Teaching"
    href:           "/teaching"
  # - name:           "Courses"
  #   href:           "/courses"
  - name:           "Résumé"
    href:           "https://javicond3.github.io/CV/CV_en.pdf"
  # - name:           "Interests"
  #   href:           "/interests"
  # - name:           "Contact"
  #   href:           "/contact"

sass:
  style:            compressed


collections:
  projects:
    output:         true
  subjects:
    output:         true

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "project"

plugins: ['jekyll/scholar']

# scholar plugin
scholar:
  style: apa
  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: publication
  bibliography_list_tag: div
  bibliography_item_tag: span