title:              "Javier Conde"
special_title:      "<span class='special_title'>J</span><span>avier</span> <span class='special_title'> C</span><span>onde</span>"
description:        "Researcher and Ph.D. student at <a href='https://www.upm.es/' target='_blank'> UPM </a> and member of <a href='http://ging.github.io/' target='_blank'> GING </a>"

url:                "null"
author:             "javicond3"
email:              "4b3javi(at)gmail.com"
location:           "Madrid, Spain"
github:             "javicond3"
linkedin:           "javier-conde-diaz"


baseurl:            ""

markdown:           kramdown

cv_link:            "https://javicond3.github.io/CV/CV_en.pdf"
nav:
  - name:           "About"
    href:           "/about"
  - name:           "CV"
    href:           "/cv"
  - name:           "Projects"
    href:           "/projects"
  # - name:           "Education"
  #   href:           "/education"
  # - name:           "Interests"
  #   href:           "/interests"
  # - name:           "Contact"
  #   href:           "/contact"

sass:
  style:            compressed


collections:
  projects:
    output:         true

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "project"

plugins: